### ISSUE TITLE
Update Classes - Jason / Luis / Jose

### ISSUE THREAD

**Issue by JasonCessna** [TicTacShen/sandbox#10]
1. Clean up Classes (Space() should be part of Board())
2. Re-define Class Types
3. Brain storm more classes - Should everything be an object? (Tokens, Turns, Activations, etc..)

**Comment by JasonCessna** [comment]
Uploaded newest update for Class Diagram.
-added a few new classes to better suit use cases
-updated classes to work together to create other classes (Board creates Player using Main Menu functions, etc)

*******This is definitely not finished; Luis please review and compare to my Use Cases. Change anything required and collaborate with Jose to ensure the classes function as Objects

**Comment by luisgz80** [comment]
I want to leave this open. I need to work on the class  diagrams and discuss with the team. I will work heavily on this and update docs for the "complete" submission whenever that is due
