### ISSUE TITLE
Update Risk Management (Mir / Ana / Jason)

### ISSUE THREAD

**Issue by JasonCessna** [TicTacShen/sandbox#13]
1. Add multi-assignment procedure to risk management document
2. Create a diagram that will show how each task is distributed (ie. 1st - Ana, 2nd - Mir, 3rd - Jose; etc) to ensure no unfair over-assignments or under-assignments in responsibility

**Comment by JasonCessna** [comment]
Also for risk management:
On holding people accountable and keeping topic-specific conversation where it belongs (the risk here being an overload of communication) we will use Github's 'Issues' feature as each assignment can have its own comment thread (as seen here), can be assigned to direct individuals (for accountability), and correlates directly to deadlines / goals (Milestones).

And time management risks can be helped by using Github's 'Milestones' feature because every issue can be assigned as a % needing to complete by a certain deadline to meet said Milestone.

**Comment by mirtaiab** [comment]
i re-uploaded the risk management plan and config plan

**Comment by mirtaiab** [comment]
let me know if any other changes
