### ISSUE TITLE
Investigate the Github Wiki (Luis / Jason)

### ISSUE THREAD

**Issue by JasonCessna** [TicTacShen/sandbox#14]
Is the Wiki a good location for documentation? Will it automatically track our progress in documentation the way this site will automatically document progress in assignments in the form of issues and progress in coding? If so, it may be superior than using Outlook (which we can still use for communication and a backup file documentation)

**Comment by luisgz80** [comment]
Google Docs may be a little easier to collaborate. I will investigate. I do not think the Wiki is a good place for documentation.

**Comment by JasonCessna** [comment]
You're probably right, I did a bit of research myself on it and it won't do well for what I had in mind; milestones, documentation change history, etc. However some of those features are already available. Feel free to close this whenever you want

**Comment by luisgz80** [comment]
@JasonCessna Dropbox might be a better experience than what we are doing in sharepoint. With Sharepoint I got the sense that switching between online edits and WORD program was a little clunky, and the webpage refresh issues when you try to switch between files...


I will pose the question in GroupMe
